using Blood_Banks.BLL;
using Blood_Banks.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Blood_Banks.UI
{
    public partial class Donors : Form
    {
        public Donors()
        {
            InitializeComponent();
        }

        donorsBLL d = new donorsBLL();
        donorDAL donordal = new donorDAL();
        string imageName = "no-image.png";
        int added_by = 1;

        private void pbdonorsClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void lbladdress_Click(object sender, EventArgs e)
        {

        }

        public void Clear()
        {
            txtUserID.Text = "";
            txtFirstname.Text = "";
            txtLastname.Text = "";
            txtEmail.Text = "";
            cmbGender.Text = "";
            cmbBloodGroup.Text = "";
            txtDonorContact.Text = "";
            txtAddress.Text = "";

            //clear the picturebox

            string path = Application.StartupPath.Substring(0, (Application.StartupPath.Length - 26));
            string imagepath = path + "\\images\\no-image.png";
            pbSelectImage.Image = new Bitmap(imagepath);
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {

            // do not need to pass the id od the donor cause it is auto generated by the db

            d.image_name = imageName;
            d.first_name = txtFirstname.Text;
            d.last_name = txtLastname.Text;
            d.email = txtEmail.Text;
            d.contact = txtDonorContact.Text;
            d.address = txtAddress.Text;
            d.email = txtEmail.Text;
            d.gender = cmbGender.Text;
            d.blood_group = cmbBloodGroup.Text;
            d.added_date = DateTime.Now;
            d.added_by = added_by;

            // adding values from the ui to the db

            bool success = donordal.Insert(d);

            if (success == true)
            {
                MessageBox.Show("Donor was added succesfully", "Insertion successful", MessageBoxButtons.OK, MessageBoxIcon.Information);
                DataTable dt = donordal.Select();
                dgvDonors.DataSource = dt;

                Clear();
            }
            else
            {
                MessageBox.Show("Donor failed to be add", "Insertion failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }




        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            Clear();
        }

        private void Donors_Load(object sender, EventArgs e)
        {
            // display donors in the dgv
            DataTable dt = donordal.Select();
            dgvDonors.DataSource = dt;
        }

        private void dgvDonors_RowHeaderMouseClick(object sender, DataGridViewCellMouseEventArgs e)
        {

        }
    }
}
